<a href="https://colab.research.google.com/github/Prav702Sarkar/First-Sem-Project/blob/main/generative_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
x=2
y=2
z=x+y
print(z)

4


In [ ]:
#expontial(**)
2**5

32

In [ ]:
5%2

1

In [ ]:
4/2

2.0

In [ ]:
5//2

2

In [ ]:
5//2.2

2.0

In [ ]:
x=2
print(x)

2


In [ ]:
a=10
b=5
a+=b
print(a)

15


In [ ]:
a=10
b=3
a//=b
print(b)

3


In [ ]:
a=17
b=20
print(a==b)
print(a!=b)
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)

False
True
False
True
False
True


In [ ]:
a=10
print(x>2 or x<10)

True


In [ ]:
my_city='solan'
type(my_city)

str

In [ ]:
my_capital='shimla'
type(my_capital)

str

In [ ]:
my_state='himachal pradesh'
type(my_state)

str

In [ ]:
my_sub="Machine learning"
my_sub[0]


'M'

In [ ]:
my_sub[-9]

' '

In [ ]:
my_sub[0:6:1]

'Machin'

In [ ]:
my_sub[15:0:-1]

'gninrael enihca'

In [ ]:
my_sub[0:12]

'Machine lear'

In [ ]:
list1=[34,64,89]
list2=[99,87,65]
my_list=list1+list2
print(my_list)

[34, 64, 89, 99, 87, 65]


In [ ]:
my_list=[89,76,56]
my_list.append(100)
print(my_list)

[89, 76, 56, 100]


In [ ]:
list1=[122,5657,90]
my_list.extend(list1)
print(my_list)

[89, 76, 56, 100, 122, 5657, 90]


In [ ]:
my_list = [23,45,67,80]
my_list.pop()
print(my_list)

[23, 45, 67]


In [ ]:
my_list.pop(1)
print(my_list)

[23, 67]


In [ ]:
my_list=[100,445,78,90]
my_list.remove(100)
print(my_list)

[445, 78, 90]


In [ ]:
my_list.index(445)

0

In [ ]:
my_list=[234,789,67,45,67,89,67]
my_list.index(67,3,6)

4

In [ ]:
my_list=[3,5,6,3,4,2,1]
my_list.sort(reverse=True)
print(my_list)

[6, 5, 4, 3, 3, 2, 1]


In [ ]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
my_list=[list1,list2,list3]
print(my_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
my_list[1][1]

5

In [ ]:
my_list[-2][-2]

5

In [ ]:
my_tuple=(1,2,3)
type(my_tuple)


tuple

In [ ]:
my_tuple=(1,2,3)
type(my_tuple)

tuple

In [ ]:
x=1,2.3
type(x)

tuple

In [ ]:
y=()
type(y)

tuple

In [ ]:
z=(True)
type(z)

bool

In [ ]:
a=("solan")
type(a)

str

In [ ]:
my_tuple1=("apple",3.24,8,True,None) #heterogeneous
type(my_tuple1)

tuple

In [ ]:
my_tuple2=(88,78,65,34)
type(my_tuple2)

tuple

In [ ]:
state_list=["HP","UP","MP","PUN","DELHI"]
capital_list=["SHM","LK","BH","CHD","ND"]
x=zip(state_list,capital_list)
x

In [ ]:
list(x)

[('HP', 'SHM'), ('UP', 'LK'), ('MP', 'BH'), ('PUN', 'CHD'), ('DELHI', 'ND')]

In [ ]:
my_tuple=(45,78,45,89,70)
my_tuple.count(45)

2

In [ ]:
my_tuple.index(78)

1

In [ ]:
tuple1=(1,2,3)
tuple2=(4,5,6)
tuple3=tuple1+tuple2
print(tuple3)

(1, 2, 3, 4, 5, 6)


In [ ]:
my_tuple=(1,2,3)
my_tuple[0]=10

TypeError: 'tuple' object does not support item assignment

In [ ]:
y= list(tuple3)
y

[1, 2, 3, 4, 5, 6]

In [ ]:
my_set=(6,8,9,10)
type(my_set)

tuple

In [ ]:
a=" "
type(a)

str

In [ ]:
b=[]
type(b)

list

In [ ]:
c=()
type(c)

tuple

In [ ]:
d={}
type(d)

dict

In [ ]:
empty_set=set()
type(empty_set)

set

In [ ]:
a=set()
a.add(10)
a

{10}

In [ ]:
a.add(20)
a

{10, 20}

In [ ]:
my_list=[56,90,78,23,12]
print(my_list)

[56, 90, 78, 23, 12]


In [ ]:
my_set={56,90,78,23,12}
print(my_set)

{23, 56, 90, 12, 78}


In [ ]:
my_set={89,45,67,78}
my_set.update((100,200,300))
print(my_set)

{67, 100, 200, 300, 45, 78, 89}


In [ ]:
my_set.remove(67)
my_set

{45, 78, 89, 200, 300}

In [ ]:
A={1,2,3,4,5}
B={4,5,6,7,8}
A.union(B)

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
A.intersection(B)

{4, 5}

In [ ]:
A.difference(B)

{1, 2, 3}

In [ ]:
B.difference(A)

{6, 7, 8}

In [ ]:
A.symmetric_difference(B)

{1, 2, 3, 6, 7, 8}

In [ ]:
#dictionary - collection of key value pair, enclosed by curly braces
#key value pair is known as item and every item seperated by comma.
#key and value seperated by colan(:)
my_dict={"HP":"SHM","UP":"LK","MP":"BH"}
type(my_dict)

dict

In [ ]:
#dictionry - it is mutable
#key - it is immutable
#value - it is mutable or immutable
my_dict={(1,2,3):"SHM","UP":"LK","MP":"BH"}
type(my_dict)

dict

In [ ]:
my_dict={"name": "Praveen", "Marks_list":[10,20,30,40]}
print(my_dict)

{'name': 'Praveen', 'Marks_list': [10, 20, 30, 40]}


In [ ]:
my_dict.update({"College":"SHOOLINI UNIVERSITY"})
print(my_dict)

{'name': 'Praveen', 'Marks_list': [10, 20, 30, 40], 'College': 'SHOOLINI UNIVERSITY'}


In [ ]:
#keys()- this method return the keys of your dictionary
my_dict.keys()

dict_keys(['name', 'Marks_list', 'College'])

In [ ]:
#values()- this method retunr values of your dictionary
list(my_dict.values())

['Praveen', [10, 20, 30, 40], 'SHOOLINI UNIVERSITY']

In [ ]:
list(my_dict.items())

[('name', 'Praveen'),
 ('Marks_list', [10, 20, 30, 40]),
 ('College', 'SHOOLINI UNIVERSITY')]

In [ ]:
my_dict.pop("name")

'Praveen'

In [ ]:
my_dict.get("name","not found")

'not found'

In [ ]:
#if condition:
    #code
#elif condition:
    #code
#else:
    #code

age=int(input("Enter your age: "))
if age<=21:
    print("You are too young for marriage")
elif age>=60:
    print("You are too old for marriage")
else:
    print("You will find your perfect match")

Enter your age: 23
You are eligible for marriage


In [ ]:
#for loop - apply on sequence(list,tuple,string,range())
my_city="solan"
for char in my_city:
    print(char)

s
o
l
a
n


In [ ]:
#indexing
for i in range(0,10,1):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(0,5):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
my_sub="Machine learning"
for i in range(len(my_sub)): #range(16)
  print(my_sub[i],i)

M 0
a 1
c 2
h 3
i 4
n 5
e 6
  7
l 8
e 9
a 10
r 11
n 12
i 13
n 14
g 15


In [ ]:
my_sub="Machine learning"
for i in range(-1,-len(my_sub)-1,-1): #range(-16)
  print(my_sub[i],i)


g -1
n -2
i -3
n -4
r -5
a -6
e -7
l -8
  -9
e -10
n -11
i -12
h -13
c -14
a -15
M -16


In [ ]:
#while loop - this loop execute upto condition is true
i = 0 #initialization
while i<5:
  print(i)
  i+=1 #increment
print(i)

0
1
2
3
4
5


In [ ]:
#loop control statement
i=0
while i<5: #condition
  i+=1     #increment
  if i==3:
    break        #break the loop
    print(i)
  else:
    print(i)

1
2


In [ ]:
#loop control statement
i=0
while i<5: #condition
  i+=1     #increment
  if i==3:
    continue #this statement skip the code
    print(i)
  else:
    print(i)

1
2
4
5


In [ ]:
#loop control statement
i=0
while i<5: #condition
  i+=1     #increment
  if i==3:
    pass        #it does not only pass
    print(i)
  else:
    print(i)

1
2
3
4
5


In [ ]:
#user defined function
def add():
  a=int(input("Enter a value: "))
  b=int(input("Enter b value: "))
  c=a+b
  print(c)
add()

Enter a value: 15
Enter b value: 20
35


In [ ]:
#calculation of two number
def calculation(a,b):
  add=a+b
  sub=a-b
  mul=a*b
  div=a/b
  return add,sub,mul,div
calculation(5,10)

(15, -5, 50, 0.5)

In [ ]:
def add(a=20,b=30):
  c=a+b
  return c
add()


50

In [ ]:
print(add(10,20))

30


In [ ]:
def interest(p,r,t):
  i=(p*r*t)/100
  return i
print(interest(1000,10,2))

200.0


In [ ]:
#available lenght argument
def test(*args):
  print(args)
  print(type(args))
  print(len(args))

test(4,5,6,7,8)

(4, 5, 6, 7, 8)
<class 'tuple'>
5


In [ ]:
def addition(*args):
  sum=0
  for i in args:
    sum+=i
  return sum
addition(1,2,3,4,5)

15

In [ ]:
def test(**kwargs):
  print(kwargs)
  print(type(kwargs))
  print(len(kwargs))
test(a=10,b=20,c=30)

{'a': 10, 'b': 20, 'c': 30}
<class 'dict'>
3


In [ ]:
def pass_students(**kwargs):
  pass_student_list=[]
  for name,marks in kwargs.items():
    if marks>=35:
      pass_student_list.append(name)
  return pass_student_list

pass_students(A=30,B=40,C=50,D=70)

['B', 'C', 'D']

In [ ]:
#how import numpy
import numpy as np #numerical python
#one dimensional array
oned_array=np.array([1,4,7])
print(oned_array)


[1 4 7]


In [ ]:
#two dimensional array
twod_array=np.array([[1,2,3],[4,5,6]])
print(twod_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
#three dimensional array
threed_array=np.array([[[1,2,3],[4,5,6]],
                      [[9,6,5],[3,4,5]]])
print(threed_array)

[[[1 2 3]
  [4 5 6]]

 [[9 6 5]
  [3 4 5]]]


In [ ]:
threed_array.ndim

3

In [ ]:
twod_array=np.array([[1,2,3],[4,5,6]])
print(twod_array)
twod_array.ndim #it returns the dimensions of array has

[[1 2 3]
 [4 5 6]]


2

In [ ]:
twod_array.shape #it stands for rows and columns

(2, 3)

In [ ]:
print(twod_array) #find datatype of the array
twod_array.dtype

[[1 2 3]
 [4 5 6]]


dtype('int64')

In [ ]:
twod_array.astype(float) #change datatype of the array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
zeros_array=np.zeros((3,4), dtype=int)
print(zeros_array) #creation of zero elementary array

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
ones_array=np.ones((3,4), dtype=int)
print(ones_array) #creation of one elementary array

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
ones_array=np.ones((3,4), dtype=int)*100
print(ones_array) #creation of hundred elementary array

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
my_array=np.full((3,4),78)
print(my_array)

[[78 78 78 78]
 [78 78 78 78]
 [78 78 78 78]]


In [ ]:
#practice code

import csv

# Example: Reading a CSV file using csv.reader
with open('data.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)  # Prints each row as a list
